//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFLOffensePassing
    {
        public Nullable<System.DateTime> date { get; set; }
        public string playerLastName { get; set; }
        public string playerFirstName { get; set; }
        public string teamNameLong { get; set; }
        public string teamNameShort { get; set; }
        public string awayOrHome { get; set; }
        public Nullable<int> completions { get; set; }
        public Nullable<int> attempts { get; set; }
        public Nullable<int> yards { get; set; }
        public Nullable<double> averageYardsPerCompletion { get; set; }
        public Nullable<int> touchdownPasses { get; set; }
        public Nullable<int> interceptionsThrown { get; set; }
        public Nullable<int> numberOfSacks { get; set; }
        public Nullable<int> yardsLostOnSacks { get; set; }
        public Nullable<double> qbr { get; set; }
        public Nullable<double> passerRating { get; set; }
        public Nullable<int> weekNumber { get; set; }
        public int recordNumber { get; set; }
    }
}
