//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFLOffenseRushing
    {
        public Nullable<System.DateTime> date { get; set; }
        public string playerLastName { get; set; }
        public string playerFirstName { get; set; }
        public string teamNameLong { get; set; }
        public string teamNameShort { get; set; }
        public string awayOrHome { get; set; }
        public Nullable<int> carries { get; set; }
        public Nullable<int> yards { get; set; }
        public Nullable<double> averageYardsPerCarry { get; set; }
        public Nullable<int> touchdowns { get; set; }
        public Nullable<int> longestCarry { get; set; }
        public Nullable<int> weekNumber { get; set; }
        public int recordNumber { get; set; }
    }
}
